
# travis-ci
---
sudo: required

services:
  - docker

env:
  - VERSION=$VERSION 

install:
  - docker build -t "freight/alpine-caddy:$VERSION" -t freight/alpine-caddy:latest .

script:
  - docker run --rm "freight/alpine-caddy:$VERSION" --version

before_deploy:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

deploy:
  provider: script
  script:  sudo docker push quay.io/freight/alpine-caddy:$VERSION &&  sudo docker push quay.io/freight/alpine-caddy:latest
  skip_cleanup: true
  on:
    branch: master
